---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# Multiple Gerrit Instances Example
name: 'Multiple Gerrit Instances'

"on":
  workflow_dispatch:

jobs:
  multi-gerrit-test:
    name: 'Test with multiple Gerrit mirrors'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: 'Start multiple Gerrit instances'
        id: gerrit
        uses: lfreleng-actions/gerrit-server-action@main
        with:
          gerrit_setup: ${{ vars.GERRIT_SETUP }}
          ssh_private_key: ${{ secrets.GERRIT_SSH_KEY }}
          base_http_port: 9000
          base_ssh_port: 30000
          sync_on_startup: true

      - name: 'Access instances'
        run: |
          echo "All Gerrit URLs: ${{ steps.gerrit.outputs.gerrit_urls }}"

          # Parse instance data
          echo '${{ steps.gerrit.outputs.instances }}' | jq '.'

          # Access specific instance
          ONAP_PORT=$(echo '${{ steps.gerrit.outputs.instances }}' |
            jq -r '.onap.http_port')
          curl "http://localhost:${ONAP_PORT}/config/server/version"
