#!/bin/bash
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# Start Gerrit instances script
# This script starts one or more Gerrit server containers based on JSON
# configuration

set -euo pipefail

echo "Starting Gerrit instances..."

# Parse configuration
INSTANCES=$(echo "$GERRIT_SETUP" | jq -c '.[]')
INSTANCE_INDEX=0

# Initialize tracking files
CONTAINER_IDS_FILE="$WORK_DIR/container_ids.txt"
INSTANCES_JSON_FILE="$WORK_DIR/instances.json"
: > "$CONTAINER_IDS_FILE"
echo "{}" > "$INSTANCES_JSON_FILE"

# Setup authentication
setup_ssh_auth() {
  local instance_dir="$1"
  local gerrit_host="$2"

  # Create SSH directory
  mkdir -p "$instance_dir/ssh"
  chmod 700 "$instance_dir/ssh"

  # Write private key
  echo "$SSH_PRIVATE_KEY" > "$instance_dir/ssh/id_rsa"
  chmod 600 "$instance_dir/ssh/id_rsa"

  # Setup known_hosts
  if [ -n "${SSH_KNOWN_HOSTS:-}" ]; then
    echo "$SSH_KNOWN_HOSTS" > "$instance_dir/ssh/known_hosts"
  else
    # Auto-fetch host key
    echo "Auto-fetching SSH host key for $gerrit_host..."
    ssh-keyscan -H "$gerrit_host" 2>/dev/null \
      > "$instance_dir/ssh/known_hosts" || {
      echo "Warning: Could not fetch SSH host key for $gerrit_host"
      touch "$instance_dir/ssh/known_hosts"
    }
  fi
  chmod 644 "$instance_dir/ssh/known_hosts"

  # Create SSH config
  cat > "$instance_dir/ssh/config" <<EOF
Host $gerrit_host
  HostName $gerrit_host
  User git
  IdentityFile /var/gerrit/ssh/id_rsa
  StrictHostKeyChecking yes
  UserKnownHostsFile /var/gerrit/ssh/known_hosts
EOF
  chmod 600 "$instance_dir/ssh/config"
}

# Generate replication.config
generate_replication_config() {
  local config_file="$1"
  local slug="$2"
  local gerrit_host="$3"
  local project="${4:-}"

  # Parse sync_refs from environment
  IFS=',' read -ra REFS <<< "$SYNC_REFS"

  cat > "$config_file" <<EOF
# Pull-replication configuration
# Auto-generated by gerrit-server-action

[gerrit]
  replicateOnStartup = $SYNC_ON_STARTUP
  autoReload = true

[replication]
  lockErrorMaxRetries = 5
  maxRetries = 5
  useCGitClient = false
  refsBatchSize = 50

[remote "$slug"]
  url = git://${gerrit_host}/\${name}.git
  timeout = $REPLICATION_TIMEOUT
  replicationDelay = 0
  replicationRetry = 60
  threads = $REPLICATION_THREADS
  createMissingRepositories = true
  replicateHiddenProjects = false
EOF

  # Add fetch refspecs
  for ref in "${REFS[@]}"; do
    echo "  fetch = $ref" >> "$config_file"
  done

  # Add project filter if specified
  if [ -n "$project" ]; then
    echo "  projects = $project" >> "$config_file"
  fi
}

# Generate secure.config for authentication
generate_secure_config() {
  local config_file="$1"
  local slug="$2"

  case "$AUTH_TYPE" in
    http_basic)
      cat > "$config_file" <<EOF
[remote "$slug"]
  username = $HTTP_USERNAME
  password = $HTTP_PASSWORD
EOF
      ;;
    bearer_token)
      cat > "$config_file" <<EOF
[auth]
  bearerToken = $BEARER_TOKEN
EOF
      ;;
    ssh)
      # No secure.config needed for SSH
      touch "$config_file"
      ;;
  esac

  chmod 600 "$config_file"
}

# Download pull-replication plugin
download_plugin() {
  local plugin_dir="$1"

  if [ "$SKIP_PLUGIN_INSTALL" = "true" ]; then
    echo "Skipping plugin download (skip_plugin_install=true)"
    return 0
  fi

  mkdir -p /tmp/gerrit-plugins
  local plugin_jar="/tmp/gerrit-plugins/pull-replication-${PLUGIN_VERSION}.jar"

  if [ -f "$plugin_jar" ]; then
    echo "Using cached plugin: $plugin_jar"
    cp "$plugin_jar" "$plugin_dir/pull-replication.jar"
    return 0
  fi

  echo "Downloading pull-replication plugin..."
  local plugin_url="https://gerrit-ci.gerritforge.com/job/plugin-pull-replication-gh-bazel-${PLUGIN_VERSION}/lastSuccessfulBuild/artifact/bazel-bin/plugins/pull-replication/pull-replication.jar"

  if curl -f -L -o "$plugin_jar" "$plugin_url" 2>/dev/null; then
    echo "Plugin downloaded ✅"
    cp "$plugin_jar" "$plugin_dir/pull-replication.jar"
  else
    echo "::warning::Failed to download plugin from CI"
    echo "::warning::attempting alternate source..."
    # Try alternate source (GitHub releases)
    local alt_url="https://github.com/GerritForge/pull-replication/releases/download/${PLUGIN_VERSION}/pull-replication.jar"
    if curl -f -L -o "$plugin_jar" "$alt_url" 2>/dev/null; then
      echo "Plugin downloaded from alternate source ✅"
      cp "$plugin_jar" "$plugin_dir/pull-replication.jar"
    else
      echo "::error::Failed to download pull-replication plugin ❌"
      return 1
    fi
  fi
}

# Download more plugins
download_additional_plugins() {
  local plugin_dir="$1"

  if [ -z "$ADDITIONAL_PLUGINS" ]; then
    return 0
  fi

  echo "Downloading additional plugins..."
  IFS=',' read -ra PLUGINS <<< "$ADDITIONAL_PLUGINS"

  for plugin_url in "${PLUGINS[@]}"; do
    plugin_name=$(basename "$plugin_url")
    echo "Downloading: $plugin_name"

    if curl -f -L -o "$plugin_dir/$plugin_name" "$plugin_url" 2>/dev/null; then
      echo "  ✅ $plugin_name"
    else
      echo "  ::warning::Failed to download $plugin_name"
    fi
  done
}

# Initialize Gerrit site
init_gerrit_site() {
  local instance_dir="$1"
  local slug="$2"
  local http_port="$3"

  echo "Initializing Gerrit site for $slug..."

  # Create directory structure
  mkdir -p "$instance_dir"/{git,cache,index,data,etc,logs,plugins,tmp}
  chmod -R 777 "$instance_dir"

  # Run Gerrit init using the container's entrypoint
  # Mount only specific subdirectories to avoid hiding /var/gerrit/bin
  docker run --rm \
    -v "$instance_dir/git:/var/gerrit/git" \
    -v "$instance_dir/cache:/var/gerrit/cache" \
    -v "$instance_dir/index:/var/gerrit/index" \
    -v "$instance_dir/data:/var/gerrit/data" \
    -v "$instance_dir/etc:/var/gerrit/etc" \
    -v "$instance_dir/logs:/var/gerrit/logs" \
    -v "$instance_dir/plugins:/var/gerrit/plugins" \
    -e CANONICAL_WEB_URL="http://localhost:$http_port" \
    "gerritcodereview/gerrit:${GERRIT_VERSION}" \
    init || {
    echo "::error::Failed to initialize Gerrit site for $slug ❌"
    return 1
  }

  echo "Gerrit site initialized ✅"
}

# Configure Gerrit
configure_gerrit() {
  local instance_dir="$1"
  local slug="$2"
  local http_port="$3"

  echo "Configuring Gerrit for $slug..."

  local config_file="$instance_dir/etc/gerrit.config"

  # Update gerrit.config
  git config -f "$config_file" gerrit.instanceId "$slug"
  git config -f "$config_file" gerrit.canonicalWebUrl \
    "http://localhost:$http_port"
  git config -f "$config_file" httpd.listenUrl "http://*:8080/"
  git config -f "$config_file" sshd.listenAddress "*:29418"

  # Set auth to development mode for testing
  git config -f "$config_file" auth.type "DEVELOPMENT_BECOME_ANY_ACCOUNT"

  # Container user
  git config -f "$config_file" container.user "root"

  # Enable replication plugin
  git config -f "$config_file" plugin.pull-replication.enabled "true"

  echo "Gerrit configured ✅"
}

# Start single instance
start_instance() {
  local instance_json="$1"
  local index="$2"

  # Parse instance config
  local project
  project=$(echo "$instance_json" | jq -r '.project // ""')
  local slug
  slug=$(echo "$instance_json" | jq -r '.slug')
  local gerrit_host
  gerrit_host=$(echo "$instance_json" | jq -r '.gerrit')

  # Calculate ports
  local http_port=$((BASE_HTTP_PORT + index))
  local ssh_port=$((BASE_SSH_PORT + index))

  echo ""
  echo "========================================"
  echo "Instance $((index + 1)): $slug"
  echo "  Project: $project"
  echo "  Source: $gerrit_host"
  echo "  HTTP Port: $http_port"
  echo "  SSH Port: $ssh_port"
  echo "========================================"

  # Instance directory
  local instance_dir="$WORK_DIR/instances/$slug"

  # Initialize site
  init_gerrit_site "$instance_dir" "$slug" "$http_port" || return 1

  # Configure Gerrit
  configure_gerrit "$instance_dir" "$slug" "$http_port" || return 1

  # Download and install plugins
  download_plugin "$instance_dir/plugins" || return 1
  download_additional_plugins "$instance_dir/plugins" || return 1

  # Setup authentication
  if [ "$AUTH_TYPE" = "ssh" ]; then
    setup_ssh_auth "$instance_dir" "$gerrit_host" || return 1
  fi

  # Generate replication configuration
  generate_replication_config "$instance_dir/etc/replication.config" \
    "$slug" "$gerrit_host" "$project"
  generate_secure_config "$instance_dir/etc/secure.config" "$slug"

  # Start container
  echo "Starting Gerrit container..."

  local container_name="gerrit-$slug"
  local cidfile="$WORK_DIR/${container_name}.cid"

  local docker_args=(
    -d
    --name "$container_name"
    --cidfile "$cidfile"
    --rm
    -p "$http_port:8080"
    -p "$ssh_port:29418"
    -v "$instance_dir/git:/var/gerrit/git"
    -v "$instance_dir/cache:/var/gerrit/cache"
    -v "$instance_dir/index:/var/gerrit/index"
    -v "$instance_dir/data:/var/gerrit/data"
    -v "$instance_dir/etc:/var/gerrit/etc"
    -v "$instance_dir/logs:/var/gerrit/logs"
    -v "$instance_dir/plugins:/var/gerrit/plugins"
    -v "$instance_dir/tmp:/var/gerrit/tmp"
    -e "CANONICAL_WEB_URL=http://localhost:$http_port"
  )

  # Add SSH volume if using SSH auth
  if [ "$AUTH_TYPE" = "ssh" ]; then
    docker_args+=(-v "$instance_dir/ssh:/var/gerrit/ssh:ro")
  fi

  # Add debug flag if enabled
  if [ "$DEBUG" = "true" ]; then
    docker_args+=(-e "DEBUG=1")
  fi

  docker run "${docker_args[@]}" \
    --pull=missing \
    "gerritcodereview/gerrit:${GERRIT_VERSION}" || {
    echo "::error::Failed to start Gerrit container for $slug ❌"
    return 1
  }

  # Wait for container to start
  sleep 2

  # Get container ID and IP
  local cid
  cid=$(cat "$cidfile")
  local container_ip
  container_ip=$(docker inspect -f \
    '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' "$cid")

  echo "$cid" >> "$CONTAINER_IDS_FILE"

  # Store instance metadata
  local temp_json
  temp_json=$(mktemp)
  jq --arg slug "$slug" \
     --arg cid "$cid" \
     --arg ip "$container_ip" \
     --argjson http_port "$http_port" \
     --argjson ssh_port "$ssh_port" \
     --arg url "http://$container_ip:8080" \
     --arg gerrit_host "$gerrit_host" \
     --arg project "$project" \
     '.[$slug] = {
       cid: $cid,
       ip: $ip,
       http_port: $http_port,
       ssh_port: $ssh_port,
       url: $url,
       gerrit_host: $gerrit_host,
       project: $project
     }' \
     "$INSTANCES_JSON_FILE" > "$temp_json"
  mv "$temp_json" "$INSTANCES_JSON_FILE"

  echo "✅ Gerrit instance started"
  echo "   Container ID: $cid"
  echo "   IP Address: $container_ip"
  echo "   HTTP URL: http://$container_ip:8080"
  echo "   SSH URL: ssh://localhost:$ssh_port"
  echo ""

  # Log container status
  if [ "$DEBUG" = "true" ]; then
    echo "Container status:"
    docker ps -f "id=$cid"
    echo ""
  fi
}

# Main loop - start all instances
while IFS= read -r instance; do
  start_instance "$instance" "$INSTANCE_INDEX" || {
    echo "::error::Failed to start instance $INSTANCE_INDEX ❌"
    exit 1
  }
  INSTANCE_INDEX=$((INSTANCE_INDEX + 1))
done <<< "$INSTANCES"

# Summary
echo "========================================"
echo "All instances started! ✅"
echo "Total instances: $INSTANCE_INDEX"
echo "========================================"
echo ""

# Add to step summary
{
  echo "**Instances Started** 🚀"
  echo ""
  echo "| Slug | HTTP Port | SSH Port | Status |"
  echo "|------|-----------|----------|--------|"
} >> "$GITHUB_STEP_SUMMARY"

for slug in $(jq -r 'keys[]' "$INSTANCES_JSON_FILE"); do
  http_port=$(jq -r ".\"$slug\".http_port" "$INSTANCES_JSON_FILE")
  ssh_port=$(jq -r ".\"$slug\".ssh_port" "$INSTANCES_JSON_FILE")
  echo "| $slug | $http_port | $ssh_port | ✅ Running |" \
    >> "$GITHUB_STEP_SUMMARY"
done

echo "" >> "$GITHUB_STEP_SUMMARY"
